services:
  - type: web
    name: javohir-portfolio
    runtime: python
    repo: https://github.com/javohirboltayev937-droid/my-portfolio
    branch: main
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput"
    startCommand: "gunicorn portfolio_pro.wsgi --workers 2 --threads 4 --timeout 60 --log-file -"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "javohir-portfolio.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://javohir-portfolio.onrender.com"
      - key: TELEGRAM_BOT_TOKEN
        value: "8240920421:AAFI_4mJmqvKiv3pd0nvwXSiAdjsyljCVpo"
      - key: TELEGRAM_CHAT_ID
        value: "8744146411"
