# Generated by Django 6.0.2 on 2026-02-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260203_1729'),
    ]

    operations = [
    ]
